# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-04 10:24
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='reported_roll_p1',
            field=otree.db.models.IntegerField(null=True, verbose_name='What number did you roll?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='reported_roll_p2',
            field=otree.db.models.IntegerField(null=True, verbose_name='What number did you roll?'),
        ),
    ]
