# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-05 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0004_auto_20181205_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q2',
        ),
    ]
