# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-05 09:46
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0005_auto_20181205_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lose_game',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
