# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 16:47
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0008_group_cumulative_payoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='actual_roll_p1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='actual_roll_p2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
