# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-17 15:25
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0015_auto_20181217_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='individual_share',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='total_contribution',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
