# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-17 15:26
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0016_auto_20181217_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contribution',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
