# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-18 08:56
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0017_player_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cumulative_payoff',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
