# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-08 08:09
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0020_remove_player_cumulative_payoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='ingame',
        ),
        migrations.AddField(
            model_name='group',
            name='ingame',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
