# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-08 08:50
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0023_auto_20190108_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='checked',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
