# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-08 12:09
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0025_auto_20190108_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ingame',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
