# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-09 07:28
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0026_auto_20190108_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='ingame',
        ),
        migrations.AddField(
            model_name='player',
            name='ingame',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
