# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-22 09:34
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0052_auto_20190122_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contribution',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
