# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-31 13:18
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0053_auto_20190122_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_amount',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
