# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-01 14:33
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0054_group_max_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Dq1',
            field=otree.db.models.IntegerField(choices=[[1, 'Extremely Unlikely'], [2, 'Moderately Unlikely'], [3, 'Somewhat Unlikely'], [4, 'Not Sure'], [5, 'Somewhat Likely'], [6, 'Moderately Likely'], [7, 'Extremely Likely']], null=True, verbose_name='Betting a day’s income at the horse races.'),
        ),
        migrations.AddField(
            model_name='player',
            name='Dq2',
            field=otree.db.models.IntegerField(choices=[[1, 'Extremely Unlikely'], [2, 'Moderately Unlikely'], [3, 'Somewhat Unlikely'], [4, 'Not Sure'], [5, 'Somewhat Likely'], [6, 'Moderately Likely'], [7, 'Extremely Likely']], null=True, verbose_name='Investing 10% of your annual income in a moderate growth mutual fund.'),
        ),
        migrations.AddField(
            model_name='player',
            name='Dq3',
            field=otree.db.models.IntegerField(choices=[[1, 'Extremely Unlikely'], [2, 'Moderately Unlikely'], [3, 'Somewhat Unlikely'], [4, 'Not Sure'], [5, 'Somewhat Likely'], [6, 'Moderately Likely'], [7, 'Extremely Likely']], null=True, verbose_name='Betting a day’s income at a high-stake poker game.'),
        ),
        migrations.AddField(
            model_name='player',
            name='Dq4',
            field=otree.db.models.IntegerField(choices=[[1, 'Extremely Unlikely'], [2, 'Moderately Unlikely'], [3, 'Somewhat Unlikely'], [4, 'Not Sure'], [5, 'Somewhat Likely'], [6, 'Moderately Likely'], [7, 'Extremely Likely']], null=True, verbose_name='Investing 5% of your annual income in a very speculative stock.'),
        ),
        migrations.AddField(
            model_name='player',
            name='Dq5',
            field=otree.db.models.IntegerField(choices=[[1, 'Extremely Unlikely'], [2, 'Moderately Unlikely'], [3, 'Somewhat Unlikely'], [4, 'Not Sure'], [5, 'Somewhat Likely'], [6, 'Moderately Likely'], [7, 'Extremely Likely']], null=True, verbose_name='Betting a day’s income on the outcome of a sporting event.'),
        ),
        migrations.AddField(
            model_name='player',
            name='Dq6',
            field=otree.db.models.IntegerField(choices=[[1, 'Extremely Unlikely'], [2, 'Moderately Unlikely'], [3, 'Somewhat Unlikely'], [4, 'Not Sure'], [5, 'Somewhat Likely'], [6, 'Moderately Likely'], [7, 'Extremely Likely']], null=True, verbose_name='Investing 10% of your annual income in a new business venture.'),
        ),
    ]
