# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-14 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0056_auto_20190201_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q9',
        ),
    ]
