# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-14 10:23
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('LCG', '0057_auto_20190214_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='MIq1',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='It would l make me feel good to be a person who has these characteristics.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq10',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I am actively involved in activities that communicate to others that I have these characteristics.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq2',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Being someone who has these characteristics is an important part of who I am.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq3',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I would be ashamed to be a person who has these characteristics.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq4',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Having these characteristics is not really important to me.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq5',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I strongly desire to have these characteristics.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq6',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='I often wear clothes that identify me as having these characteristics.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq7',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The types of things I do in my spare time (e.g. hobbies) clearly identify me as having these characteristics. '),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq8',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The kinds of books and magazines that I read identify me as having these characteristics.'),
        ),
        migrations.AddField(
            model_name='player',
            name='MIq9',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='The fact that I have these characteristics is communicated to others by my membership in certain organizations.'),
        ),
    ]
